### ISSUE TITLE
How to use vendor based on this boilerplate

### ISSUE THREAD

**Issue by TengfeiQi** [enricodeleo/vue-parceljs-starter#1]
Hi Deleo, 
   Great starter 👍, thanks for sharing ☺️
   I wanna to know how to support vendor? I want to create vendor.js and app.js files for my project in which the vendor.js file contains the base lib such as Vue.js and Vue-router Vuex core code, and main.js only contains the Vue.js code written for my app.

**Comment by enricodeleo** [comment]
Hi, you want to read parcel documentation here and code consequently to let the bundler split as you require https://parceljs.org/code_splitting.html
